### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by ashutosh1919** [yy/dviz-course#34]
Professor @yy , I found a link which is broken `m01`. [A simple IPython notebook that explores the map and Voronoi diagram](https://github.com/yy/dviz-course/blob/master/w01-intro/cholera_map/john-snow-cholera-map.ipynb) is broken. I couldn't find it anywhere on this repo. So, requesting you to fix it or send it here and I will be happy to raise PR.

**Comment by yy** [comment]
Thanks!
