### ISSUE TITLE
Rendering Notebook diffs

### ISSUE THREAD

**Issue by ashutosh1919** [yy/dviz-course#36]
Professor @yy , I have recently raised PR to add one of the feature and noticed that we currently don't have anything which can tell us the diffs in the notebooks changed in case somebody raises a PR. But there is a way in which we can setup a github workflow which will tell the changes in notebook same way git VCS works. We can use [ReviewNB](https://www.reviewnb.com/) for that. Let me know how this idea sound to you. If you think it will be helpful to us, then I will be happy to start working on that.

**Comment by yy** [comment]
great idea. I think I've just installed the reviewnb app. do we need to setup a workflow additionally?

**Comment by ashutosh1919** [comment]
Professor @yy ,  Yes. We need to write a new Github workflow to do that. I will do it and will raise PR.

**Comment by ashutosh1919** [comment]
ReviewNB is integrated and is tested by #37. Hence, closing this issue.
