### ISSUE TITLE
Squashing before merging PR commits

### ISSUE THREAD

**Issue by ashutosh1919** [yy/dviz-course#52]
Professor @yy, I noticed while working on some PRs (#51 and #48) that the repository doesn't have squashing enabled yet. Squashing is nothing but combining all the commits of the PR into a single one and merging the PR as a single commit. If this is something that you think is helpful, then you just need to enable the squash merging in the [repository setting](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests). 

Once this feature is enabled, we don't need to do anything else. From next time onwards, You will see option `Squash and Merge` on all PRs. Instead of just `Merge`, you can click on `Squash and Merge` and it will squash all the commits into single commit.

**Advantage of Squash Merge:**
- Experimental commits to test features must not be committed while merging and only the final result of all commits in PR should be merged as a single commit.
- If PRs have a high number of commits and if we keep merging that, then the `.git` history size will become very huge in just some months. It will be many times more than the actual repository code itself.

Please close this issue once you see this.

**Comment by yy** [comment]
thanks! It's actually enabled but it's an old habit. ^^;
