### ISSUE TITLE
Broken Links and GitHub Workflow

### ISSUE THREAD

**Issue by ashutosh1919** [yy/dviz-course#54]
Professor @yy, We have previously seen such a scenario in #34  where we found the broken link while manually reading the material. Instead of relying on manually checking the links after a certain duration, it is good to have a workflow to check links' health status.

As part of the new PR #53, I have added that workflow. After running the workflow, I found out some of links are broken. I have listed all of the broken links with paths below:
- `m03-integrity/class.md `
     - ![](http://ecx.images-amazon.com/images/I/51FKg7ecS%2BL._SX334_BO1,204,203,200_.jpg)
          - Above image is accessible if you click on the link, but we can't access it from workflow because it is stored on the amazon server and maybe they are returning XML which will not be compatible with HTTP requests. To solve that, what we can do is, we can store the same image to our dropbox publically or in the code repository itself and we can use that link. (Happy to raise the PR to do that).
- `m04-perception/class.md`
     - Bang Wong, from "Points of View" (they are very short columns): http://clearscience.info/wp/?p=546
     - [Weber's law and thresholds](https://www.khanacademy.org/science/health-and-medicine/nervous-system-and-sensory-infor/sensory-perception-2014-03-27T18:45:20.451Z/v/webers-law-and-thresholds)
- `m05-design/class.md`
     - Bateman et al., [Useful junk?: the effects of visual embellishment on comprehension and memorability of charts](http://ww.w.cedma-europe.org/newsletter%20articles/misc/The%20Effects%20of%20Visual%20Embellishment%20on%20Comprehension%20and%20Memorability%20of%20Charts.pdf)
     - Borkin et al., [What Makes a Visualization Memorable?](http://ieeexplore.ieee.org/xpl/login.jsp?tp=&arnumber=6634103&url=http%3A%2F%2Fieeexplore.ieee.org%2Fxpls%2Fabs_all.jsp%3Farnumber%3D6634103)
- `m12-maps/class.md`
     - [What's the best map projection?](http://usersguidetotheuniverse.com/index.php/2011/03/03/whats-the-best-map-projection/)
     - [R. Knippers: Map projections](http://kartoweb.itc.nl/geometrics/map%20projections/mappro.html)

**Comment by ashutosh1919** [comment]
Professor @yy , Can you please provide me corrected links for above broken links? I will raise PR to fix it.

**Comment by yy** [comment]
Thanks!

- Yes, the book image can be somewhere else. 
- Bang Wong, points of view series: http://blogs.nature.com/methagora/2013/07/data-visualization-points-of-view.html
- Weber's law: https://www.khanacademy.org/test-prep/mcat/processing-the-environment/sensory-perception/v/webers-law-and-thresholds
- useful junk: https://dl.acm.org/doi/pdf/10.1145/1753326.1753716
- Borkin et al: https://ieeexplore.ieee.org/iel7/2945/6634084/06634103.pdf
- map projection links: remove

**Comment by ashutosh1919** [comment]
![51FKg7ecS+L _SX334_BO1,204,203,200_](https://user-images.githubusercontent.com/20843596/133619037-e827b3d6-4914-4e12-b30e-9030d03d1b88.jpg)
