### ISSUE TITLE
Documentation with Mkdocs 

### ISSUE THREAD

**Issue by fralfaro** [yy/dviz-course#80]
Hello, I have made a port of the course with [mkdocs](https://squidfunk.github.io/mkdocs-material/). The repository is at [fralfaro/dviz-course](https://github.com/fralfaro/dviz-course) and the documentation is at [fralfaro.github.io/dviz-course](https://fralfaro.github.io/dviz-course).

I hope this can centralize the course, to improve the learning experience.

**Comment by yy** [comment]
Very cool! Will it be ok to incorporate your version here?

**Comment by fralfaro** [comment]
You need to approve this [PR](https://github.com/yy/dviz-course/pull/81)

**Comment by yy** [comment]
Thanks!!
